/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include <time.h>
/* 
*	Point_1
*/

#define PERIPH_BASE 0x40000000
#define PERIPH_BIT_BAND 0x42000000			/* allias */
#define AHB1_BASE PERIPH_BASE + 0x00020000



/* GPIOD/GPIOA, not used */
#define GPIOD_BASE AHB1_BASE + 0x0C00		//0x40020C00
#define GPIOD ((GPIO_STRUCT *) GPIOD_BASE)
#define GPIOA ((GPIO_STRUCT *) AHB1_BASE)

/* 
*	Point_2
*/
typedef struct
{
   uint32_t MODER;
   uint32_t OTYPER;
   uint32_t OSPEEDR;
   uint32_t PUPDR;
   uint32_t IDR;
   uint32_t ODR;
   uint32_t BSRR;
   uint32_t LCKR;
   uint32_t AFR[2];
} GPIO_STRUCT;

#define GPIOC_BASE (AHB1_BASE + 0x0800)
#define GPIOC ((GPIO_STRUCT *) GPIOC_BASE)




/*
 * Lab 1
 * Var_4
*/ 

/* Bit-band */
#define BIT(address, bit) *((uint32_t *) (PERIPH_BIT_BAND + ( (uint32_t)address - PERIPH_BASE)*32 + bit*4))

/* Define buttons and Leds */
#define RED_BUTTON_PIN 5
#define BLUE_BUTTON_PIN 6
#define RED_LED_PIN 9
#define BLUE_LED_PIN 8

/* Value range */
const uint32_t MAX_VAL = 3;
const uint32_t MIN_VAL = 0;



/* delay */
void delay(int milliseconds)
{
    long pause;
    clock_t now,then;

    pause = milliseconds*(CLOCKS_PER_SEC/1000);
    now = then = clock();
    while( (now-then) < pause )
        now = clock();
}

void my_delay(long int t){
    for (int i = 0; i < t; i++);
}





int incrementValue(int value)
{
	if (value == MAX_VAL) return value;
	return value + 1;
}

int decrementValue(int value)
{
	if (value == MIN_VAL) return value;
	return value - 1;
}

void updateLedTest(int value)
{
	if (value == 0){
		GPIOC->ODR &= ~(1 << RED_LED_PIN);
		GPIOC->ODR &= ~(1 << BLUE_LED_PIN);
	} else if (value == 1) {
		GPIOC->ODR |= 1 << RED_LED_PIN;
		GPIOC->ODR &= ~(1 << BLUE_LED_PIN);
	} else if (value == 2) {
		GPIOC->ODR &= ~(1 << RED_LED_PIN);
		GPIOC->ODR |= 1 << BLUE_LED_PIN;
	} else if (value == 3) {
		GPIOC->ODR |= 1 << RED_LED_PIN;
		GPIOC->ODR |= 1 << BLUE_LED_PIN;
	}
}

void updateLed(int value)
{
	BIT(&GPIOC->ODR, RED_LED_PIN) = (value >> 0) & 1; // Red for 0-bit of number
	BIT(&GPIOC->ODR, BLUE_LED_PIN) = (value >> 1) & 1; // Blue for 1-bit of number
}


int main(void)
{
	*((uint32_t *) 0x40023830) |= 1 | 4;

	GPIOC->MODER |= (1<<(BLUE_LED_PIN*2)); // 8 pin
	GPIOC->MODER |= (1<<(RED_LED_PIN*2)); // 9 pin

	int CURR_VALUE = 0;
	updateLed(CURR_VALUE);




	uint32_t button_red = BIT(&GPIOC->IDR, RED_BUTTON_PIN);		// Bit-band
	uint32_t button_blue = GPIOC->IDR & 1 << BLUE_BUTTON_PIN;	// IDR	

    /* Loop forever */
	for(;;)
	{
		uint32_t button_red_curr = BIT(&GPIOC->IDR, RED_BUTTON_PIN);									//GPIOC->IDR & 1 << RED_BUTTON_PIN;
		uint32_t button_blue_curr = GPIOC->IDR & 1 << BLUE_BUTTON_PIN;	// IDR

		if (button_red != button_red_curr){
			CURR_VALUE = incrementValue(CURR_VALUE);
			updateLed(CURR_VALUE);
			delay(500);
		}

		if (button_blue!= button_blue_curr){
			CURR_VALUE = decrementValue(CURR_VALUE);
			updateLed(CURR_VALUE);
			delay(500);
		}

	}
}
